Master
NPLPackages/paracraft pull request #10
Opened 2017-07-04 07:28 UTC by hetter

add  "pop_moive_mode" filter

2017-07-05 03:20 UTC, LiXizhi requested changes

2017-07-05 03:20 UTC, LiXizhi commented on script/apps/Aries/Creator/Game/Movie/MovieManager.lua
> +	GameLogic.GetFilters():apply_filters("pop_moive_mode", self.lastmode);
spelling is wrong  `movie`

2017-07-05 03:34 UTC, hetter reviewed
correct the spelling

2017-07-13 14:46 UTC, LiXizhi approved these changes

2017-07-13 14:47 UTC, merged